### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by cliu5** [mzhao3/Poppins#1]
The images are compelling in getting the user to want to interact with the data further. Also, the data pertains to issues relevant to us as highschoolers so that increases user experience. A question I have is whether you will connect all three data sets together into one big visual. What if the user wants to see how all the different factors interact?🥇 👍 💯

**Comment by KaitlinWan** [comment]
No. We will be keeping our datasets separate. If time allows, we will try to incorporate all data sets into one visual graph. Thanks for the comments! 😄
