### ISSUE TITLE
rev_A

### ISSUE THREAD

**Issue by JabirC** [mzhao3/Poppins#2]
The data presented here is very compelling and is very relevant to us, as high school students. It’s clear how the user can switch between different representations of the data, and between representations of different data; however, is there any way for the user to play around with the data displays themselves by adjusting certain features of it? Also, a lot of the visualization is switching between representations of different data surrounding the same issue; it would be cool to see how these can come together and interact with each other.

**Comment by KaitlinWan** [comment]
Hi Jabir,
Thanks for the comments. We will be trying to allow users to filter the information. For example, if a user would like to see schools from only ONE district, he/she will be able to indicate that and the graph will change accordingly. If time allows, we will try to create another graph to compare data as a whole.
Team Poppins
