### ISSUE TITLE
rev_D

### ISSUE THREAD

**Issue by JabirC** [mzhao3/Poppins#5]
I think a better experience could be encouraged by having the data displayed together. Right now the different sets are represented by switching between different views, which is good, but I think that displaying the different data against each other would allow for more thoughtful comparison and contemplation of the questions that the project aims to answer.

**Comment by KaitlinWan** [comment]
Hi Jabir, 
If time allows, we will try out best to create a new graph with the whole data. Thanks for the comments!
Team Poppins 👩
